import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { NeboComponent } from '../src/nebo-config';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <NeboComponent slug='dashboard' />
      </main>
    </div>
  )
}
